import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#006a63',
        'inverse-on-surface': '#f3f0ef',
        'on-primary-container': '#a3faef',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#80d5cb',
        secondary: '#a73a00',
        'primary-container': '#0f766e',
        'on-tertiary-fixed': '#370e00',
        'surface-container-low': '#f6f3f2',
        'on-tertiary-fixed-variant': '#72361b',
        'on-secondary-fixed': '#370e00',
        'outline-variant': '#bdc9c6',
        tertiary: '#7f4025',
        primary: '#005c55',
        'surface-dim': '#dcd9d9',
        'secondary-fixed': '#ffdbce',
        'on-tertiary': '#ffffff',
        'on-background': '#1c1b1b',
        'on-tertiary-container': '#ffe5db',
        'surface-container-high': '#eae7e7',
        'on-primary-fixed-variant': '#00504a',
        'on-primary-fixed': '#00201d',
        'on-surface': '#1c1b1b',
        'surface-container-highest': '#e5e2e1',
        'on-surface-variant': '#3e4947',
        'primary-fixed-dim': '#80d5cb',
        'on-secondary': '#ffffff',
        'surface-variant': '#e5e2e1',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#ffb598',
        'tertiary-fixed': '#ffdbce',
        'primary-fixed': '#9cf2e8',
        'on-secondary-container': '#571a00',
        'inverse-surface': '#313030',
        'tertiary-container': '#9c573a',
        outline: '#6e7977',
        'error-container': '#ffdad6',
        'surface-bright': '#fcf9f8',
        surface: '#fcf9f8',
        'secondary-fixed-dim': '#ffb599',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#7f2b00',
        'on-error-container': '#93000a',
        'surface-container': '#f0eded',
        background: '#fcf9f8',
        'secondary-container': '#fd651e',
      },
      fontFamily: {
        headline: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        label: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
} satisfies Config
