/**
 * Màu đồng bộ Stitch project 6347238164431372939 (designTheme.namedColors + tailwind extend).
 */
export const stitchColors = {
  surfaceTint: '#006a63',
  inverseOnSurface: '#f3f0ef',
  onPrimaryContainer: '#a3faef',
  surfaceContainerLowest: '#ffffff',
  inversePrimary: '#80d5cb',
  secondary: '#a73a00',
  primaryContainer: '#0f766e',
  onTertiaryFixed: '#370e00',
  surfaceContainerLow: '#f6f3f2',
  onTertiaryFixedVariant: '#72361b',
  onSecondaryFixed: '#370e00',
  outlineVariant: '#bdc9c6',
  tertiary: '#7f4025',
  primary: '#005c55',
  surfaceDim: '#dcd9d9',
  secondaryFixed: '#ffdbce',
  onTertiary: '#ffffff',
  onBackground: '#1c1b1b',
  onTertiaryContainer: '#ffe5db',
  surfaceContainerHigh: '#eae7e7',
  onPrimaryFixedVariant: '#00504a',
  onPrimaryFixed: '#00201d',
  onSurface: '#1c1b1b',
  surfaceContainerHighest: '#e5e2e1',
  onSurfaceVariant: '#3e4947',
  primaryFixedDim: '#80d5cb',
  onSecondary: '#ffffff',
  surfaceVariant: '#e5e2e1',
  error: '#ba1a1a',
  onPrimary: '#ffffff',
  tertiaryFixedDim: '#ffb598',
  tertiaryFixed: '#ffdbce',
  primaryFixed: '#9cf2e8',
  onSecondaryContainer: '#571a00',
  inverseSurface: '#313030',
  tertiaryContainer: '#9c573a',
  outline: '#6e7977',
  errorContainer: '#ffdad6',
  surfaceBright: '#fcf9f8',
  surface: '#fcf9f8',
  secondaryFixedDim: '#ffb599',
  onError: '#ffffff',
  onSecondaryFixedVariant: '#7f2b00',
  onErrorContainer: '#93000a',
  surfaceContainer: '#f0eded',
  background: '#fcf9f8',
  secondaryContainer: '#fd651e',
} as const

export type StitchColorKey = keyof typeof stitchColors
